name: Deploy FastAPI app to Azure Web App

on:
  push:
    branches:
      - master  # غيّرها لـ master لو الفرع عندك اسمه master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-app
        path: .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: eye-care-api       # <-- غيّرها لو اسم App Service مختلف
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
